config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  devise_for :users

  resources :proponents do
    collection do
      get :calculate_inss
      get :group_calculate_inss
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/export_csv', to: 'dashboard#export_csv'

  root to: 'dashboard#index'

  mount Sidekiq::Web => "/sidekiq"  # login: user senha: 123
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :proponent
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :proponent

  enum contact_type: { telefone_residencial: 'telefone_residencial', celular: 'celular', whatsapp: 'whatsapp', email: 'email' }
end

app/models/proponent.rb
# frozen_string_literal: true

class Proponent < ApplicationRecord
  scope :by_discount_inss_count, lambda {
    select('discount_inss, COUNT(*) AS count')
      .group('discount_inss')
  }

  MAX_PROPONENT_PER_PAGE = 5

  paginates_per MAX_PROPONENT_PER_PAGE

  # Dependendo da criticidade da informação o mais correto seria usar uma gem like paranoia
  # https://github.com/rubysherpas/paranoia
  # para que não possivel excluir registro do banco.

  has_many :addresses, dependent: :destroy
  has_many :contacts, dependent: :destroy

  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  validates :name, :document, :birthday, :salary, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    @groups_calculate_inss = Proponent.by_discount_inss_count
  end

  def export_csv
    ExportJob.perform_later(filters, current_user)

    redirect_to root_path, notice: 'Gerando relátorio, cheque seu email'
  end

  private

  def filters
    {} # sanatização em params e etc.
  end
end

app/controllers/proponents_controller.rb
# frozen_string_literal: true

class ProponentsController < ApplicationController
  def index
    @proponents = Proponent.page(params[:page])
  end

  def show
    @proponent = Proponent.find(params[:id])
  end

  def new
    @proponent = ProponentFactory.build
  end

  def edit
    @proponent = Proponent.find(params[:id])
  end

  def create
    @result_set = CreateProponentService.call(proponent_params)
    @proponent = @result_set.payload[:proponent]

    if @result_set.success?
      redirect_to @proponent, notice: 'Proponent criado com sucesso.'
    else
      render :new
    end
  end

  def update
    @result_set = UpdateProponentService.call(params[:id], proponent_params)
    @proponent = @result_set.payload[:proponent]

    if @result_set.success?
      redirect_to @proponent, notice: 'Proponent atualizado com sucesso.'
    else
      render :edit
    end
  end

  def calculate_inss
    salary = params[:salary].to_i
    discount_inss = InssCalculatorService.call(salary)
    render json: { discount_inss: discount_inss }
  end

  def group_calculate_inss
    render json: { payload: Proponent.by_discount_inss_count.as_json }
  end

  private

  def proponent_params
    params.require(:proponent).permit(:name, :document, :birthday, :salary,
                                      addresses_attributes: %i[id public_place number neighborhood city state zip_code _destroy],
                                      contacts_attributes: %i[id contact_type value _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/proponents_helper.rb
# frozen_string_literal: true

module ProponentsHelper
end

app/views/dashboard/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Meu Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <!-- Você pode adicionar outros links aqui -->
          </ul>
        
        </div>
      </div>
    </nav>

    <div class="container my-4">
      <h1>Bem-vindo ao Dashboard</h1>
      <% if notice.present? %>
          <div class="alert alert-info" role="alert">
            <%= notice %>
          </div>
        <% end %>
      <div class="d-flex justify-content-between  mb-4">
        <%= link_to 'Ver Proponentes', proponents_path, class: "btn btn-primary" %>
        <%= link_to 'Exportar CSV', dashboard_export_csv_path, class: "btn btn-primary" %>
      </div>

      <div class="row g-4">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              Desconto INSS por faixa
            </div>
            <div class="card-body">
              <canvas id="doughnutChart" width="400" height="400"></canvas>
            </div>
          </div>
        </div>

        <table class="table table-striped table-bordered table-hover align-middle">
        <thead class="table-dark">
          <tr>
            <th>Taxa</th>
            <th>Qtd proponentes</th>
          </tr>
        </thead>

        <tbody>
          <% @groups_calculate_inss.each do |group_calculate_inss| %>
            <tr>
              <td><%= group_calculate_inss.discount_inss %></td>
              <td><%= group_calculate_inss.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      </div>
    </div>

    <script>
    function generateHexColors(n) {
      const colors = [];
      for (let i = 0; i < n; i++) {
        const randomNum = Math.floor(Math.random() * 0xFFFFFF);
        const hexString = randomNum.toString(16).padStart(6, '0');
        const color = `#${hexString}`;
        colors.push(color);
      }
      return colors;
      // normalmente isso deveria ser uma paleta de cores!
    }
  
    document.addEventListener("DOMContentLoaded", function() {
        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
  
        fetch(`/proponents/group_calculate_inss`, {
          headers: {
            'X-CSRF-Token': csrfToken,
            'Accept': 'application/json'
          },
          credentials: 'same-origin'
        })
        .then(response => response.json())
        .then(data => {
          const chartData = data.payload;

          let doughnutData = {
            labels: chartData.map(item => item.discount_inss),
            datasets: [{
              label: 'My First Dataset',
              data: chartData.map(item => item.count),
              backgroundColor: generateHexColors(chartData.length),
              hoverOffset: 4
            }]
          };
  
          const doughnutConfig = {
            type: 'doughnut',
            data: doughnutData,
          };
  
          const doughnutCtx = document.getElementById('doughnutChart').getContext('2d');
          new Chart(doughnutCtx, doughnutConfig);
        });
    });
  </script>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioInss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proponents/_address_fields.html.erb
<li class="nested-fields card p-3 mb-3">
  <h4 class="mb-3">Endereço</h4>

  <div class="row g-3">
    <div class="col-md-3">
      <%= form.label :zip_code, class: "form-label" %>
      <%= form.text_field :zip_code, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :public_place, class: "form-label" %>
      <%= form.text_field :public_place, class: "form-control" %>
    </div>

    <div class="col-md-3">
      <%= form.label :number, class: "form-label" %>
      <%= form.text_field :number, class: "form-control" %>
    </div>

    <div class="col-md-4">
      <%= form.label :neighborhood, class: "form-label" %>
      <%= form.text_field :neighborhood, class: "form-control" %>
    </div>
  </div>

  <div class="mt-3">
    <%= link_to_remove_association 'Remover', form, class: 'btn btn-outline-danger' %>
  </div>
</li>

app/views/proponents/_contact_fields.erb
<li class="nested-fields card p-3 mb-3">
  <h4 class="mb-3">Contato</h4>

  <div class="row g-3">
    <div class="col-md-6">
      <%= form.label :value, class: "form-label" %>
      <%= form.text_field :value, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :contact_type, class: "form-label" %>
      <%= form.select :contact_type, Contact.contact_types.keys.map { |key| [key.humanize, key] }, 
                  { include_blank: true }, 
                  { class: "form-control" } %>

      <!-- Obvio que dependendo deveria ter umas MASK adequada, mas como isso é uma POC rápida eu skipei -->
    </div>
  </div>

  <div class="mt-3">
    <%= link_to_remove_association 'Remover', form, class: 'btn btn-outline-danger' %>
  </div>
</li>

app/views/proponents/_form.html.erb
<div class="form">
  <%= form_with(model: proponent, local: true, html: { class: "needs-validation" }) do |form| %>
    <% if proponent.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(proponent.errors.count, "error") %> prohibited this proponent from being saved:</h2>
        <ul>
          <% proponent.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row g-3">
      <div class="col-md-6">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="col-md-6">
        <%= form.label :document, class: "form-label" %>
        <%= form.text_field :document, class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= form.label :birthday, class: "form-label" %>
        <%= form.date_field :birthday, class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= form.label :salary, class: "form-label" %>
        <%= form.number_field :salary, class: "form-control" %>
      </div>
    </div>

    <div >
        <p id='calculate_inss'> </p>   
    </div>

    <div class="mb-3">
      <%= link_to_add_association 'Adicionar Endereço', form, :addresses, form_name: 'form',
        'data-association-insertion-method' => 'prepend', 
        'data-association-insertion-node' => "#addresses-proponent ol",
        class: "btn btn-secondary" %>
    </div>

    <fieldset id="addresses-proponent" class="mb-3">
      <ol class="list-unstyled">
        <%= form.fields_for :addresses do |address| %>
          <%= render partial: 'address_fields', locals: { form: address } %>
        <% end %>
      </ol>
    </fieldset>

    <div class="mb-3">
      <%= link_to_add_association 'Adicionar contato', form, :contacts, form_name: 'form',
        'data-association-insertion-method' => 'prepend', 
        'data-association-insertion-node' => "#contacts-proponent ol",
        class: "btn btn-secondary" %>
    </div>

    <fieldset id="contacts-proponent" class="mb-3">
      <ol class="list-unstyled">
        <%= form.fields_for :contacts do |contact| %>
          <%= render partial: 'contact_fields', locals: { form: contact } %>
        <% end %>
      </ol>
    </fieldset>

    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>


<script> 
  const getInss = function(salary) {
    const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

    fetch(`/proponents/calculate_inss?salary=${salary}`, {
      headers: {
        'X-CSRF-Token': csrfToken,
        'Accept': 'application/json'
      },
      credentials: 'same-origin' 
    })
      .then(response => response.json())
      .then(data => {
        const paragraph = document.getElementById('calculate_inss');
        paragraph.innerHTML=data.discount_inss
      }
    );
  }

  const inputSalary = document.getElementById('proponent_salary');
  inputSalary.addEventListener('input', (event) => {
    getInss(event.target.value);
  });
</script>

app/views/proponents/edit.html.erb
<div class="container">
  <h1 class="mb-4">Editando Proponente</h1>

  <%= render 'form', proponent: @proponent %>

  <div class="mt-3 d-flex gap-2">
    <%= link_to 'Mostrar', @proponent, class: "btn btn-primary" %>
    <%= link_to 'Voltar', proponents_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/proponents/index.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>

<table class="table table-striped table-bordered table-hover align-middle">
  <thead class="table-dark">
    <tr>
      <th>Nomes</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @proponents.each do |proponent| %>
      <tr>
        <td><%= proponent.name %></td>
        <td><%= link_to 'Mostrar', proponent, class: 'btn btn-sm btn-primary' %></td>
        <td><%= link_to 'Editar', edit_proponent_path(proponent), class: 'btn btn-sm btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-between align-items-center mt-3">
  <%= link_to 'Novo Proponente', new_proponent_path, class: 'btn btn-success' %>
  <nav aria-label="Proponent pages" class="mt-3 d-flex justify-content-center">
    <%= paginate @proponents, params: { controller: 'proponents', action: 'index' } %>
  </nav>
</div>

app/views/proponents/new.html.erb
<div class="container">
  <h1 class="mb-4">Novo Proponente</h1>

  <%= render 'form', proponent: @proponent %>

  <%= link_to 'Voltar', proponents_path, class: "btn btn-outline-secondary mt-3" %>
</div>

app/views/proponents/show.html.erb
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">Detalhes do Proponente</h5>
    <p class="card-text">
      <strong>Nome:</strong> <%= @proponent.name %>
    </p>
    <p class="card-text">
      <strong>Desconto Inss:</strong> <%= @proponent.discount_inss %>
    </p>
    <p class="card-text">
      <strong>Contatos:</strong> <%= @proponent.contacts.map {  |contact| contact.value } %>
    </p>
    <div class="d-flex gap-2">
      <%= link_to 'Edit', edit_proponent_path(@proponent), class: "btn btn-primary" %>
      <%= link_to 'Back', proponents_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>